/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({ 'title' : IDL.Text, 'completed' : IDL.Bool });
export const PublicUserProfile = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'username' : IDL.Text,
  'tasksCompletedToday' : IDL.Nat,
  'totalStudyMinutes' : IDL.Nat,
  'totalPoints' : IDL.Nat,
});
export const TaskUpdateAction = IDL.Variant({
  'delete' : IDL.Null,
  'complete' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text], [], []),
  'dailyTaskReset' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
  'getMyProfile' : IDL.Func([], [PublicUserProfile], ['query']),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [PublicUserProfile],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logStudySession' : IDL.Func([IDL.Nat], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
  'updateTask' : IDL.Func([IDL.Text, TaskUpdateAction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({ 'title' : IDL.Text, 'completed' : IDL.Bool });
  const PublicUserProfile = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'username' : IDL.Text,
    'tasksCompletedToday' : IDL.Nat,
    'totalStudyMinutes' : IDL.Nat,
    'totalPoints' : IDL.Nat,
  });
  const TaskUpdateAction = IDL.Variant({
    'delete' : IDL.Null,
    'complete' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text], [], []),
    'dailyTaskReset' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PublicUserProfile)], ['query']),
    'getMyProfile' : IDL.Func([], [PublicUserProfile], ['query']),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [PublicUserProfile],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logStudySession' : IDL.Func([IDL.Nat], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
    'updateTask' : IDL.Func([IDL.Text, TaskUpdateAction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };