/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PublicUserProfile {
  'tasks' : Array<Task>,
  'username' : string,
  'tasksCompletedToday' : bigint,
  'totalStudyMinutes' : bigint,
  'totalPoints' : bigint,
}
export interface Task { 'title' : string, 'completed' : boolean }
export type TaskUpdateAction = { 'delete' : null } |
  { 'complete' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string], undefined>,
  'dailyTaskReset' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<PublicUserProfile>>,
  'getMyProfile' : ActorMethod<[], PublicUserProfile>,
  'getPublicUserProfile' : ActorMethod<[Principal], PublicUserProfile>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[bigint], undefined>,
  'setUsername' : ActorMethod<[string], undefined>,
  'updateTask' : ActorMethod<[string, TaskUpdateAction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];